spring:
  datasource:
    url: jdbc:postgresql://ec2-54-243-107-66.compute-1.amazonaws.com:5432/dakbkelg915trh?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
    username: vdapezarpldmrs
    password: 7c5339b08e6a611dcd6a218b9c6250865ecd8501c4bacc5e13ec58a03521ea2b
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate